### ISSUE TITLE
PSQL QUERY ERROR on updating json fields with nested objects containing arrays

### ISSUE THREAD

**Issue by kurmetaubanov** [ash-project/ash_postgres#297] opened 2024-05-21 19:19 UTC
**Describe the bug**
hi Zach! 
I have a `res` resource with map attribute `:json`
on update, i call `Domain.update_res(res, %{json: json})`
and i get `QUERY ERROR`, with some arrays in the objects of json transformed to:
`%{"some_object" =>  dynamic([], fragment( "(ARRAY[?])", ....`

**To Reproduce**
clone [https://github.com/kurmetaubanov/reproduce_ash_json_bug](https://github.com/kurmetaubanov/reproduce_ash_json_bug)
run ash_postgres migrations
run project iex -S mix phx.server
go to `page_controller.ex` to get the json object that causes issue

**Expected behavior**
json field should be updated without issues

** Runtime
 - Elixir version 1.16.1-otp-26
 - Erlang version 26.2.2
 - OS Ubuntu 22.04
 - Ash version 3.0.2
 - Ash postgres 2.0.0

Screenshot of issue
![image](https://github.com/ash-project/ash_postgres/assets/49303566/883d9d99-0c20-4459-88f3-07375ae3e9cd)

**Comment by zachdaniel** [comment] 2024-05-22 18:54
Duplicate of: https://github.com/ash-project/ash_postgres/issues/299

**Closed** 2024-05-22 21:48 UTC
Labels: bug
