### ISSUE TITLE
Custom index unexpectedly dropped when upgrading to 2.0

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_postgres#284] opened 2024-05-15 05:34 UTC
**Describe the bug**
When using attribute-base multitenancy and upgrading to Ash Postgres 2.0, the migration generator will drop any define custom_indexs

**To Reproduce**
With an existing resource and snapshot that has a custom index such as:
```elixir
    custom_indexes do
      index [:environment_key, :key]
    end
  end
```

And with the latest release, the migration generator will produce:
```elixir
  def up do
    drop_if_exists index(:accounts, [:organization_id, :environment_key, :key])
  end
```

**Expected behavior**
I would expect no change to the index.

**Additional context**
Discussed here:
https://discord.com/channels/711271361523351632/711271361523351636/1240164223775146035

**Comment by zachdaniel** [comment] 2024-05-15 11:16
Very strange. What changed about the snapshot? This would be pretty hard to debug after the fact

**Comment by zachdaniel** [comment] 2024-05-15 15:19
Could you tell me what your snapshot had for that custom index under `all_tenants?` before you did the upgrade?

**Comment by rgraff** [comment] 2024-05-15 16:51
I diff'ed the snapshots, and saw a few expected changes but not under `custom_indexes`. @sevenseacat said she had a repo that could reproduce.

**Comment by zachdaniel** [comment] 2024-05-15 18:09
Oh, awesome. In that case @sevenseacat can you point me to it?

**Comment by rgraff** [comment] 2024-05-15 18:47
@zachdaniel I'll have a diff shortly too. Working on it now

**Comment by sevenseacat** [comment] 2024-05-16 01:41
its not in a repo but I managed to reproduce it with one of my existing apps. 

I have a resource with no multitenancy, and a custom index - 

```elixir
 postgres do
    custom_indexes do
      index "name gin_trgm_ops", name: "artists_name_gin_index", using: "GIN"
    end
  end
```

The current snapshot for this resource looks like:

```json
  "custom_indexes": [
    {
      "message": null,
      "name": "artists_name_gin_index",
      "table": null,
      "include": null,
      "prefix": null,
      "fields": [
        {
          "type": "string",
          "value": "name gin_trgm_ops"
        }
      ],
      "where": null,
      "unique": false,
      "using": "GIN",
      "nulls_distinct": true,
      "error_fields": [],
      "all_tenants?": false,
      "concurrently": false
    }
  ],
```

As soon as I added a dummy multitenancy by attribute:

```elixir
    multitenancy do
      strategy :attribute
      attribute :id
    end
```

And generated migrations, the index got dropped and was *not* recreated.

```elixir
drop_if_exists index(:artists, [:id, "name gin_trgm_ops"], name: "artists_name_gin_index")
```

Some other foreign keys on the resource were dropped and recreated in what looks like the exact same way.

The new snapshot still has the index in it and it looks exactly the same - 

```json
  "custom_indexes": [
    {
      "message": null,
      "name": "artists_name_gin_index",
      "table": null,
      "include": null,
      "prefix": null,
      "where": null,
      "fields": [
        {
          "type": "string",
          "value": "name gin_trgm_ops"
        }
      ],
      "unique": false,
      "using": "GIN",
      "all_tenants?": false,
      "error_fields": [],
      "concurrently": false,
      "nulls_distinct": true
    }
  ],
```

**Comment by zachdaniel** [comment] 2024-05-16 05:15
Okay, so, I've fixed this insofar it should now properly *add*  the indexes after removing. When changing certain aspects of multitenancy, we drop and recreate indexes.

**Comment by zachdaniel** [comment] 2024-05-16 05:15
Fix is in `main`

**Closed by zachdaniel** 2024-05-16 05:15 UTC
Labels: bug
