### ISSUE TITLE
Aggregates on `{:array, ...}` types fail when arrays are empty

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_postgres#120] opened 2022-11-30 05:44 UTC
**Describe the bug**
Looks like postgres doesn't like aggregates on arrays, where there are empty arrays

**To Reproduce**
A user resource contains:

```elixir
attribute :roles, {:array, :atom}
```

A related resource with an aggregate on the user resource:

```elixir
first :roles, :user, :roles
```

When you load the aggregate, if there are any users with no roles, the following error is raised: 

```
ERROR 2202E (array_subscript_error) cannot accumulate empty arrays
```

**Expected behavior**
No error

**Runtime**
 - Elixir version 1.14
 - Erlang version 25
 - Ash version 2.4.15
 - Ash postgres version 1.1.2
 - Postgres version 13

**Comment by zachdaniel** [comment] 2022-11-30 17:21
This one is actually pretty wacky :/

@totaltrash does the workaround mentioned in `discord` work for you?

```elixir
first :roles, :user, :roles do
  filter expr(array_field != [])
end

calculate ..., expr(:role in (roles || []))
```

**Comment by zachdaniel** [comment] 2022-11-30 17:21
Its pretty hard to generalize a solution to this one...

**Comment by totaltrash** [comment] 2022-11-30 22:35
@zachdaniel unfortunately it doesn't, the aggregate resolves to nil, regardless of whether the filter matches or not. I've tried loading the aggregate separately (no change)

**Comment by zachdaniel** [comment] 2022-11-30 22:43
If you get some time to add a test to ash_postgres I'd be really grateful. Or show two minimal resources that reproduce the issue. Just to make sure I have the whole picture.

**Comment by zachdaniel** [comment] 2022-12-01 17:21
So TIL that there is no such thing as "nested arrays" in postgres and that appears to be the primary cause of this issue. Or something related to what `array_agg` does to an array. So realistically for compatibility with array types I need to find a way to do the `list` and `first` aggregates without using `array_agg`

**Comment by totaltrash** [comment] 2022-12-01 22:01
Is something like this possible (as part of the extensions installed by the migrator)? https://stackoverflow.com/a/48915348/2384351

**Comment by zachdaniel** [comment] 2022-12-01 22:03
I've been looking at this all day TBH, trying to figure out how to make an aggregate function do what we need it to do 😭 That one just flattens all the values into a single list.

**Comment by zachdaniel** [comment] 2022-12-01 22:03
I think that `list` type aggregates will never work with arrays inside of postgres. Or at least not for a while. But I'm trying to see if there is something I can do to support the `first` type aggregate.

**Comment by zachdaniel** [comment] 2022-12-02 01:24
I'm going to close this issue for now, primarily because there are workarounds and its just not worth the effort to fix at the moment. In the meantime, I've added a compile time error message to inform users that they cannot use `:list` and `:first` aggregate types with `{:array` type attributes. An enterprising soul could likely fix this case for `:first` but not for `:list`.

**Closed by zachdaniel** 2022-12-02 01:24 UTC
Labels: bug
